export const types = {
    FETCH_FLIGHT_REPORTS: 'FETCH_FLIGHT_REPORTS',
    FETCH_FLIGHT_REPORT: 'FETCH_FLIGHT_REPORT',
    DELETE_FLIGHT_REPORT: 'DELETE_FLIGHT_REPORT',
    UPDATE_FLIGHT_REPORT: 'UPDATE_FLIGHT_REPORT',
    CREATE_FLIGHT_REPORT: 'CREATE_FLIGHT_REPORT',
    FETCH_FLIGHT_REPORT_GRAPH: 'FETCH_FLIGHT_REPORT_GRAPH',
    FETCH_FLIGHT_REPORT_SELECTOR: 'FETCH_FLIGHT_REPORT_SELECTOR',
    SET_CURRENT_FLIGHT_REPORT: 'SET_CURRENT_FLIGHT_REPORT',
    EXPORT_FLIGHT_REPORT: 'EXPORT_FLIGHT_REPORT'
};