export const types = {
    FETCH_MANUFACTURERS: 'FETCH_MANUFACTURERS',
    FETCH_MANUFACTURER: 'FETCH_MANUFACTURER',
    DELETE_MANUFACTURER: 'DELETE_MANUFACTURER',
    UPDATE_MANUFACTURER: 'UPDATE_MANUFACTURER',
    CREATE_MANUFACTURER: 'CREATE_MANUFACTURER',

    SET_CURRENT_MANUFACTURER: 'SET_CURRENT_MANUFACTURER',
};