export const types = {
    FETCH_LOCALIZATIONS: 'FETCH_LOCALIZATIONS',
    FETCH_LOCALIZATION: 'FETCH_LOCALIZATION',
    DELETE_LOCALIZATION: 'DELETE_LOCALIZATION',
    UPDATE_LOCALIZATION: 'UPDATE_LOCALIZATION',
    CREATE_LOCALIZATION: 'CREATE_LOCALIZATION',

    SET_CURRENT_LOCALIZATION: 'SET_CURRENT_LOCALIZATION',
};