export const types = {
    FETCH_CRASH_REPORTS: 'FETCH_CRASH_REPORTS',
    FETCH_CRASH_REPORT: 'FETCH_CRASH_REPORT',
    DELETE_CRASH_REPORT: 'DELETE_CRASH_REPORT',
    UPDATE_CRASH_REPORT: 'UPDATE_CRASH_REPORT',
    CREATE_CRASH_REPORT: 'CREATE_CRASH_REPORT',
    FETCH_CRASH_REPORT_GRAPH: 'FETCH_CRASH_REPORT_GRAPH',
    FETCH_CRASH_REPORT_SELECTOR: 'FETCH_CRASH_REPORT_SELECTOR',
    SET_CURRENT_CRASH_REPORT: 'SET_CURRENT_CRASH_REPORT',
};