export const types = {
    FETCH_OPERATORS: 'FETCH_OPERATORS',
    FETCH_OPERATOR: 'FETCH_OPERATOR',
    DELETE_OPERATOR: 'DELETE_OPERATOR',
    UPDATE_OPERATOR: 'UPDATE_OPERATOR',
    CREATE_OPERATOR: 'CREATE_OPERATOR',

    SET_CURRENT_OPERATOR: 'SET_CURRENT_OPERATOR',
};