export const types = {
    FETCH_PROJECTS: 'FETCH_PROJECTS',
    FETCH_PROJECT: 'FETCH_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    FETCH_PROJECTS_SELECTOR: 'FETCH_PROJECTS_SELECTOR',
    SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
};