export const types = {
    FETCH_DRONE_TYPES: 'FETCH_DRONE_TYPES',
    FETCH_DRONE_TYPE: 'FETCH_DRONE_TYPE',
    DELETE_DRONE_TYPE: 'DELETE_DRONE_TYPE',
    UPDATE_DRONE_TYPE: 'UPDATE_DRONE_TYPE',
    CREATE_DRONE_TYPE: 'CREATE_DRONE_TYPE',

    SET_CURRENT_DRONE_TYPE: 'SET_CURRENT_DRONE_TYPE',
};