export const types = {
    FETCH_DRONES: 'FETCH_DRONES',
    FETCH_DRONE: 'FETCH_DRONE',
    DELETE_DRONE: 'DELETE_DRONE',
    UPDATE_DRONE: 'UPDATE_DRONE',
    CREATE_DRONE: 'CREATE_DRONE',

    SET_CURRENT_DRONE: 'SET_CURRENT_DRONE',
};